/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InnerTableQueryChildInformation {
    #[serde(rename = "rule")]
    pub rule: i32,
    #[serde(rename = "children")]
    pub children: Vec<models::InnerTableQuery>,
}

impl InnerTableQueryChildInformation {
    pub fn new(
        rule: i32,
        children: Vec<models::InnerTableQuery>,
    ) -> InnerTableQueryChildInformation {
        InnerTableQueryChildInformation { rule, children }
    }
}
