/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use super::InnerTableQuery;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InnerTableQueryChildInformation {
    #[serde(rename = "rule")]
    pub rule: usize,
    #[serde(rename = "headIndex")]
    pub head_index: usize,
    #[serde(rename = "children")]
    pub children: Vec<InnerTableQuery>,
}

impl From<InnerTableQueryChildInformation>
    for nemo::execution::tracing::node_query::TableEntriesForTreeNodesQuerySuccessor
{
    fn from(value: InnerTableQueryChildInformation) -> Self {
        Self {
            rule: value.rule,
            head_index: value.head_index,
            children: value.children.into_iter().map(Into::into).collect(),
        }
    }
}
