/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableQueryBaseTableEntriesPagination {
    #[serde(rename = "start")]
    pub start: i32,
    #[serde(rename = "count")]
    pub count: i32,
}

impl TableQueryBaseTableEntriesPagination {
    pub fn new(start: i32, count: i32) -> TableQueryBaseTableEntriesPagination {
        TableQueryBaseTableEntriesPagination { start, count }
    }
}
