/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableQueryBaseTableEntriesPagination {
    #[serde(rename = "start")]
    pub start: usize,
    #[serde(rename = "count")]
    pub count: usize,
}

impl From<TableQueryBaseTableEntriesPagination>
    for nemo::execution::tracing::shared::PaginationQuery
{
    fn from(value: TableQueryBaseTableEntriesPagination) -> Self {
        Self {
            start: value.start,
            count: value.count,
        }
    }
}
