/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableQueryBaseTableEntries {
    #[serde(rename = "queries", skip_serializing_if = "Option::is_none")]
    pub queries: Option<Vec<models::TableEntryQuery>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::TableQueryBaseTableEntriesPagination>>,
}

impl TableQueryBaseTableEntries {
    pub fn new() -> TableQueryBaseTableEntries {
        TableQueryBaseTableEntries {
            queries: None,
            pagination: None,
        }
    }
}
