/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableResponseBaseTableEntries {
    #[serde(rename = "entries")]
    pub entries: Vec<models::TableEntryResponse>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::TableResponseBaseTableEntriesPagination>,
}

impl TableResponseBaseTableEntries {
    pub fn new(
        entries: Vec<models::TableEntryResponse>,
        pagination: models::TableResponseBaseTableEntriesPagination,
    ) -> TableResponseBaseTableEntries {
        TableResponseBaseTableEntries {
            entries,
            pagination: Box::new(pagination),
        }
    }
}
