/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TableEntryQuery {
    String(String),
    Number(usize),
}

impl Default for TableEntryQuery {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

impl From<TableEntryQuery> for nemo::execution::tracing::shared::TableEntryQuery {
    fn from(value: TableEntryQuery) -> Self {
        match value {
            TableEntryQuery::String(query) => Self::Query(query),
            TableEntryQuery::Number(entry) => Self::Entry(entry),
        }
    }
}
