/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use super::TableQueryBaseTableEntries;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct TableQueryBase {
    #[serde(rename = "tableEntries", skip_serializing_if = "Option::is_none")]
    pub table_entries: Option<Box<TableQueryBaseTableEntries>>,
}
