/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableEntryResponse {
    /// each table result gets some kind of id (maybe just index); this is the only way to query facts that feature nulls
    #[serde(rename = "entryId")]
    pub entry_id: i32,
    #[serde(rename = "termTuple")]
    pub term_tuple: Vec<String>,
}

impl TableEntryResponse {
    pub fn new(entry_id: i32, term_tuple: Vec<String>) -> TableEntryResponse {
        TableEntryResponse {
            entry_id,
            term_tuple,
        }
    }
}
