/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use super::{TableEntryResponse, TableResponseBaseTableEntriesPagination};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableResponseBaseTableEntries {
    #[serde(rename = "entries")]
    pub entries: Vec<TableEntryResponse>,
    #[serde(rename = "pagination")]
    pub pagination: Box<TableResponseBaseTableEntriesPagination>,
}
