/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableResponseBaseMetaInformation {
    #[serde(rename = "executionTime")]
    pub execution_time: usize,
}

impl From<TableResponseBaseMetaInformation>
    for nemo::execution::tracing::shared::ResponseMetaInformation
{
    fn from(value: TableResponseBaseMetaInformation) -> Self {
        Self {
            execution_time: value.execution_time,
        }
    }
}

impl From<nemo::execution::tracing::shared::ResponseMetaInformation>
    for TableResponseBaseMetaInformation
{
    fn from(value: nemo::execution::tracing::shared::ResponseMetaInformation) -> Self {
        Self {
            execution_time: value.execution_time,
        }
    }
}
