/*
 * Generated by cue.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use super::{Rule, TableResponseBaseTableEntries, TreeForTableResponseChildInformation};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TreeForTableResponse {
    #[serde(rename = "childInformation", skip_serializing_if = "Option::is_none")]
    pub child_information: Option<Box<TreeForTableResponseChildInformation>>,
    #[serde(rename = "predicate")]
    pub predicate: String,
    #[serde(rename = "tableEntries")]
    pub table_entries: Box<TableResponseBaseTableEntries>,
    #[serde(rename = "possibleRulesAbove")]
    pub possible_rules_above: Vec<Rule>,
    #[serde(rename = "possibleRulesBelow")]
    pub possible_rules_below: Vec<Rule>,
}

impl From<TreeForTableResponse> for nemo::execution::tracing::tree_query::TreeForTableResponse {
    fn from(value: TreeForTableResponse) -> Self {
        let entries = value
            .table_entries
            .entries
            .into_iter()
            .map(Into::into)
            .collect::<Vec<_>>();
        let pagination = (*value.table_entries.pagination).into();

        Self {
            predicate: value.predicate,
            entries,
            pagination,
            possible_rules_above: value
                .possible_rules_above
                .into_iter()
                .map(Into::into)
                .collect(),
            possible_rules_below: value
                .possible_rules_below
                .into_iter()
                .map(Into::into)
                .collect(),
            next: value.child_information.map(|info| (*info).into()),
        }
    }
}

impl From<nemo::execution::tracing::tree_query::TreeForTableResponse> for TreeForTableResponse {
    fn from(value: nemo::execution::tracing::tree_query::TreeForTableResponse) -> Self {
        let table_entries = Box::new(TableResponseBaseTableEntries {
            entries: value.entries.into_iter().map(Into::into).collect(),
            pagination: Box::new(value.pagination.into()),
        });

        Self {
            child_information: value.next.map(|next| Box::new(next.into())),
            predicate: value.predicate,
            table_entries,
            possible_rules_above: value
                .possible_rules_above
                .into_iter()
                .map(Into::into)
                .collect(),
            possible_rules_below: value
                .possible_rules_below
                .into_iter()
                .map(Into::into)
                .collect(),
        }
    }
}
