//! This module defines [ProgramHandle].

use std::rc::Rc;

use crate::{
    error::warned::Warned,
    parser::{Parser, span::CharacterPosition},
    rule_file::RuleFile,
    rule_model::{
        components::{ComponentSource, ProgramComponent, rule::Rule, statement::Statement},
        error::{TranslationReport, ValidationReport},
        origin::Origin,
        pipeline::{
            ProgramPipeline, commit::ProgramCommit, id::ProgramComponentId,
            transformations::ProgramTransformation,
        },
        programs::{ProgramRead, ProgramWrite, program::Program},
        translation::{ASTProgramTranslation, ProgramParseReport},
    },
};

/// Program-like object that is a spefic revision within [ProgramPipeline]
#[derive(Debug, Clone)]
pub struct ProgramHandle {
    /// Reference to the [ProgramPipeline]
    pipeline: Rc<ProgramPipeline>,

    /// Revision this object is a handle for
    revision: usize,
}

impl ProgramHandle {
    /// Create a new [ProgramHandle] from a reference to a [ProgramPipeline]
    /// and a revision number.
    pub(crate) fn new(pipeline: Rc<ProgramPipeline>, revision: usize) -> Self {
        Self { pipeline, revision }
    }

    /// Return a [ProgramHandle] to the original revision of this handle's
    /// [ProgramPipeline], i.e. the first revision (the program as it was created
    /// from the user input).
    pub fn original_revision(&self) -> ProgramHandle {
        self.pipeline.clone().original_revision()
    }

    /// Create a [ProgramHandle] from a [RuleFile].
    pub fn from_file(
        file: &RuleFile,
    ) -> Result<Warned<Self, TranslationReport>, ProgramParseReport> {
        let parser = Parser::initialize(file.content());
        let ast = parser.parse().map_err(|(_tail, report)| report)?;

        let pipeline = ProgramPipeline::new();
        // Record the source so that component origins can later be resolved
        // to source positions (line and column numbers).
        pipeline.set_source(file.content());

        let mut commit = ProgramCommit::empty(pipeline, ValidationReport::default());

        ASTProgramTranslation::default()
            .translate(&ast, &mut commit)
            .warned(commit.submit().expect("No validation has occurred yet"))
    }

    /// Create a new [ProgramCommit] representing an empty program
    /// that contains a copy of the [ValidationReport] from the given handle.
    pub fn fork(&self) -> ProgramCommit {
        let report = self.pipeline.revision(self.revision).report().clone();

        ProgramCommit::empty(self.pipeline.clone(), report)
    }

    /// Create a new [ProgramCommit] representing an exact copy of the given program.
    pub fn fork_full(&self) -> ProgramCommit {
        let report = self.pipeline.revision(self.revision).report().clone();
        let statements = self.pipeline.revision(self.revision).statements();

        ProgramCommit::new(self.pipeline.clone(), statements, report)
    }

    /// Apply a [ProgramTransformation] to this program.
    pub fn transform<Transformation: ProgramTransformation>(
        &self,
        transformation: Transformation,
    ) -> Result<ProgramHandle, ValidationReport> {
        transformation.apply(self)
    }

    /// Return a reference to the [ValidationReport]
    /// attached to this handle.
    pub fn report(&self) -> &ValidationReport {
        self.pipeline.revision(self.revision).report()
    }

    /// Create a [Program] from this handle.
    pub fn materialize(&self) -> Program {
        let mut program = Program::default();

        for statement in self.statements() {
            program.add_statement(statement.clone());
        }

        program
    }

    /// Returns a reference to the [ProgramComponent] of the given [ProgramComponentId],
    /// if it exists.
    pub fn component(&self, id: ProgramComponentId) -> Option<&dyn ProgramComponent> {
        self.pipeline.find_component(id)
    }

    /// Given a [ProgramComponentId] return the corresponding [Rule], if it exists.
    pub fn rule_by_id(&self, id: ProgramComponentId) -> Option<&Rule> {
        self.pipeline.rule_by_id(id)
    }

    /// Return the [Rule] at the given index, counting rules only.
    pub fn rule_by_index(&self, index: usize) -> Option<&Rule> {
        self.rules().nth(index)
    }

    /// Return the position (1-based line and column) of the given component
    /// in the original source text.
    ///
    /// Returns `None` if the program was not parsed from a source file, or if the
    /// component does not directly originate from the source (for example because
    /// it was generated by a transformation). In the latter case, resolve the
    /// component to its origin first.
    pub fn source_position<Component>(&self, component: &Component) -> Option<CharacterPosition>
    where
        Component: ComponentSource<Source = Origin>,
    {
        let Origin::File { start, .. } = component.origin() else {
            return None;
        };

        Some(self.pipeline.source_positions()?.position(start))
    }
}

impl ProgramRead for ProgramHandle {
    fn statements(&self) -> impl Iterator<Item = &Statement> {
        self.pipeline
            .revision(self.revision)
            .statements()
            .map(|&id| self.pipeline.statement(id))
    }
}

impl From<Program> for ProgramHandle {
    fn from(program: Program) -> Self {
        let mut commit = ProgramCommit::empty(ProgramPipeline::new(), ValidationReport::default());

        for statement in program.statements() {
            commit.add_statement(statement.clone());
        }

        commit
            .submit()
            .expect("no validation performed, so no errors possible")
    }
}
