# These are required on macOS, as the extension cannot be linked
# against libpython. See also
# https://pyo3.rs/v0.14.2/building_and_distribution.html#macos
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[alias]
xtask = "run --package xtask --"