name: Build with nix

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  evaluate:
    name: Make sure that the nix flake evaluates and run the checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix flake check
