name: Build with nix

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build using the nix flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: nix flake check
