name: Build with nix

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  evaluate:
    name: Make sure that the nix flake evaluates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v1
    - run: nix flake check

  build-nemo:
    name: Build nemo using the nix flake
    needs: evaluate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v1
    - run: nix build .#nemo

  build-python:
    needs: build-nemo
    name: Build nemo-python using the nix flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v1
    - run: nix build .#nemo-python

  build-wasm:
    needs: build-nemo
    name: Build nemo-wasm using the nix flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v1
    - run: nix build .#nemo-wasm

  test-python:
    needs: build-python
    name: Test nemo-python using the nix flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v1
    - run: nix run .#python3 -- -m unittest discover -s nemo-python/tests -v
