name: Build with nix

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  build-nemo:
    name: Build nemo using the nix flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nemo

  build-python:
    name: Build nemo-python using the nix flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nemo-python

  build-wasm:
    name: Build nemo-wasm using the nix flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nemo-wasm

  evaluate:
    name: Make sure that the nix flake evaluates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
