name: Build Releases
on:
  release:
    types: [created]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build rust binary
        run: cargo build --workspace --release --target=x86_64-unknown-linux-gnu && strip target/release/nmo

      - name: Create archive
        run: mv target/release/nmo . && tar -cf nmo-linux-gnu.tar.gz nmo README.md LICENSE-APACHE LICENSE-MIT

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: nmo-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # needs to be provided to change assets

  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build rust binary
        run: cargo build --workspace --release --target=x86_64-pc-windows-gnu

      - name: Create archive
        run: mv target/release/nmo . && 7z a -tzip nmo-windows-gnu nmo README.md LICENSE-APACHE LICENSE-MIT

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: nmo-windows-gnu.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # needs to be provided to change assets

