name: Build Releases
on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            name: amd64-windows
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
            name: amd64-linux
          # - target: x86_64-apple-darwin
          #   archive: zip
          #   name: amd64-macos
    steps:
      - uses: actions/checkout@v3
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # needs to be provided to change assets
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE-APACHE LICENSE-MIT"
          TOOLCHAIN_VERSION: nightly
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: ${{ format('nemo_{0}_{1}', github.ref_name, matrix.name) }}
